export function validateGraph(nodes, edges) {
  const ids=new Set(nodes.map(n=>n.id));
  const errors=[];
  for(const e of edges){if(!ids.has(e.from)||!ids.has(e.to))errors.push(`Broken connection: ${e.id}`);if(e.from===e.to)errors.push(`Self connection: ${e.from}`)}
  return {ok:errors.length===0,errors};
}

export function androidProjectManifest(project,nodes){
  const name=(project||'ARK App').replace(/[^A-Za-z0-9 ]/g,'').trim()||'ARK App';
  const permissions=[];
  const add=p=>{if(!permissions.includes(p))permissions.push(p)};
  for(const n of nodes){if(n.type==='Camera'||n.type==='AI Vision'||n.type==='Object Detector')add('android.permission.CAMERA');if(n.type==='Microphone')add('android.permission.RECORD_AUDIO');if(n.type==='GPS')add('android.permission.ACCESS_FINE_LOCATION');if(['Web Request','API','Download','Upload'].includes(n.type))add('android.permission.INTERNET');if(n.type==='Bluetooth')add('android.permission.BLUETOOTH_CONNECT')}
  return {name,permissions};
}

export function generateAndroidFiles(project,nodes,edges){
  const manifest=androidProjectManifest(project,nodes);
  const appClass=`package com.ark.generated;\n\nimport android.app.Activity;\nimport android.os.Bundle;\n\npublic class MainActivity extends Activity {\n  @Override public void onCreate(Bundle state) { super.onCreate(state); }\n}`;
  const permissions=manifest.permissions.map(p=>`    <uses-permission android:name="${p}" />`).join('\n');
  const xml=`<?xml version="1.0" encoding="utf-8"?>\n<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n${permissions}\n    <application android:theme="@style/AppTheme" android:label="${manifest.name}">\n        <activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity>\n    </application>\n</manifest>`;
  return {'README.md':`# Generated by ARK App Builder\n\nProject: ${manifest.name}\nNodes: ${nodes.length}\nConnections: ${edges.length}\n\nThis starter project is generated from the ARK visual graph.\n`,'app/src/main/java/com/ark/generated/MainActivity.java':appClass,'app/src/main/AndroidManifest.xml':xml};
}
