import React, { useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const catalog = [
 ['UI',['Button','Text','Image','Image Button','Input','Slider','Switch']],
 ['Logic',['Event','If / Else','Variable','Timer','Loop']],
 ['Device',['Camera','Microphone','Audio','File','USB','Bluetooth','GPS','Sensor']],
 ['Network',['Web Request','API','Download','Upload']],
 ['AI',['AI Vision','AI Text','AI Assistant','Object Detector']],
 ['Data',['Local Storage','Database','JSON']],
 ['Navigation',['Page','Open Page','Back','Dialog','Bottom Sheet']],
 ['System',['Notification','Permission','Clipboard','Share','Vibrate']]
];

const meta={
 Button:{title:'Button',props:{text:'Button'}},Text:{title:'Text',props:{text:'Hello ARK'}},Image:{title:'Image',props:{src:''}},'Image Button':{title:'Image Button',props:{src:'',action:'click'}},Input:{title:'Text Input',props:{hint:'Type here'}},Slider:{title:'Slider',props:{min:0,max:100,value:50}},Switch:{title:'Switch',props:{checked:false}},
 Event:{title:'On Click',props:{event:'click'}},'If / Else':{title:'Condition',props:{expression:'true'}},Variable:{title:'Variable',props:{name:'value',value:'0'}},Timer:{title:'Timer',props:{ms:1000}},Loop:{title:'Loop',props:{count:3}},Camera:{title:'Camera',props:{}},Microphone:{title:'Microphone',props:{}},Audio:{title:'Audio',props:{file:''}},File:{title:'File',props:{mode:'open'}},USB:{title:'USB / Pendrive',props:{}},Bluetooth:{title:'Bluetooth',props:{}},GPS:{title:'GPS',props:{}},Sensor:{title:'Sensor',props:{type:'accelerometer'}},
 'Web Request':{title:'Web Request',props:{url:'',method:'GET'}},API:{title:'API',props:{baseUrl:''}},Download:{title:'Download',props:{url:''}},Upload:{title:'Upload',props:{url:''}},
 'AI Vision':{title:'AI Vision',props:{provider:'local',model:'auto'}},'AI Text':{title:'AI Text',props:{provider:'local',model:'auto'}},'AI Assistant':{title:'AI Assistant',props:{provider:'local',model:'auto'}},'Object Detector':{title:'Object Detector',props:{model:'auto',confidence:0.5}},
 'Local Storage':{title:'Local Storage',props:{key:'data'}},Database:{title:'Database',props:{name:'app.db'}},JSON:{title:'JSON',props:{mode:'parse'}},
 Page:{title:'Page',props:{name:'Home'}},'Open Page':{title:'Open Page',props:{page:'Home'}},Back:{title:'Back',props:{}},Dialog:{title:'Dialog',props:{title:'Message',message:'Hello'}},'Bottom Sheet':{title:'Bottom Sheet',props:{title:'Options'}},
 Notification:{title:'Notification',props:{title:'ARK',message:'Hello'}},Permission:{title:'Permission',props:{permission:'camera'}},Clipboard:{title:'Clipboard',props:{text:''}},Share:{title:'Share',props:{text:''}},Vibrate:{title:'Vibrate',props:{ms:200}}
};

const uid=()=>crypto.randomUUID();
const newNode=(type,index=0)=>({id:uid(),type,title:meta[type]?.title||type,x:80+(index%5)*250,y:75+Math.floor(index/5)*175,enabled:true,props:{...(meta[type]?.props||{})}});

function downloadText(name,text,type='text/plain'){
 const blob=new Blob([text],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url);
}

function generateAndroidProject(project,nodes){
 const appName=project.replace(/[^a-zA-Z0-9 ]/g,'').trim()||'ARK App';
 const packageName=`com.arkbuilder.${appName.toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,24)||'app'}`;
 const permissions=[...new Set(nodes.flatMap(n=>n.type==='Camera'?['android.permission.CAMERA']:n.type==='Microphone'?['android.permission.RECORD_AUDIO']:n.type==='GPS'?['android.permission.ACCESS_FINE_LOCATION']:n.type==='Bluetooth'?['android.permission.BLUETOOTH_CONNECT','android.permission.BLUETOOTH_SCAN']:n.type==='Notification'?['android.permission.POST_NOTIFICATIONS']:[]))];
 const activity=`package ${packageName};\n\nimport android.app.Activity;\nimport android.os.Bundle;\nimport android.graphics.Color;\nimport android.widget.TextView;\n\npublic class MainActivity extends Activity {\n @Override public void onCreate(Bundle state){ super.onCreate(state); TextView v=new TextView(this); v.setText(\"${appName.replace(/"/g,'\\"')}\\nGenerated by ARK App Builder\"); v.setTextColor(Color.WHITE); v.setTextSize(20); v.setPadding(32,64,32,32); v.setBackgroundColor(Color.rgb(7,10,15)); setContentView(v); }\n}\n`;
 const manifest=`<?xml version="1.0" encoding="utf-8"?>\n<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n${permissions.map(p=>` <uses-permission android:name="${p}" />`).join('\n')}\n <application android:theme="@style/AppTheme" android:label="${appName}">\n  <activity android:name=".MainActivity" android:exported="true">\n   <intent-filter>\n    <action android:name="android.intent.action.MAIN"/>\n    <category android:name="android.intent.category.LAUNCHER"/>\n   </intent-filter>\n  </activity>\n </application>\n</manifest>\n`;
 const gradle=`plugins { id 'com.android.application' version '8.7.3' apply false }\n`;
 const settings=`pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nrootProject.name='${appName.replace(/'/g,'')}'\ninclude ':app'\n`;
 const appGradle=`plugins { id 'com.android.application' }\n\nandroid { namespace '${packageName}'; compileSdk 35\n defaultConfig { applicationId '${packageName}'; minSdk 26; targetSdk 35; versionCode 1; versionName '1.0' } }\n`;
 const strings=`<resources><string name="app_name">${appName}</string></resources>`;
 const styles=`<resources><style name="AppTheme" parent="android:style/Theme.Material.NoActionBar"><item name="android:fontFamily">sans</item><item name="android:colorAccent">#59d9ff</item><item name="android:navigationBarColor">#070a0f</item><item name="android:statusBarColor">#070a0f</item></style></resources>`;
 const graph={schema:'ark-project',version:3,project,packageName,nodes};
 return {appName,packageName,permissions,files:{'settings.gradle':settings,'build.gradle':gradle,'app/build.gradle':appGradle,'app/src/main/AndroidManifest.xml':manifest,`app/src/main/java/${packageName.replace(/\\./g,'/')}/MainActivity.java`:activity,'app/src/main/res/values/strings.xml':strings,'app/src/main/res/values/styles.xml':styles,'ark-project.json':JSON.stringify(graph,null,2)}};
}

function App(){
 const [nodes,setNodes]=useState([]); const [edges,setEdges]=useState([]); const [selected,setSelected]=useState(null); const [project,setProject]=useState('My ARK App'); const [zoom,setZoom]=useState(1); const [query,setQuery]=useState(''); const [connectFrom,setConnectFrom]=useState(null); const [buildLog,setBuildLog]=useState('Ready'); const [generated,setGenerated]=useState(null);
 const fileInput=useRef(null);
 const selectedNode=useMemo(()=>nodes.find(n=>n.id===selected),[nodes,selected]);
 const filtered=catalog.map(([g,items])=>[g,items.filter(i=>i.toLowerCase().includes(query.toLowerCase()))]).filter(([,items])=>items.length);
 const addNode=type=>{const n=newNode(type,nodes.length);setNodes(v=>[...v,n]);setSelected(n.id)};
 const updateNode=(id,patch)=>setNodes(v=>v.map(n=>n.id===id?{...n,...patch}:n));
 const updateProp=(key,value)=>selectedNode&&updateNode(selectedNode.id,{props:{...selectedNode.props,[key]:value}});
 const connect=(from,to)=>{if(!from||from===to)return;setEdges(v=>v.some(e=>e.from===from&&e.to===to)?v:[...v,{id:uid(),from,to}]);setConnectFrom(null)};
 const autoConnect=()=>{const es=[];for(let i=0;i<nodes.length-1;i++)es.push({id:uid(),from:nodes[i].id,to:nodes[i+1].id});setEdges(es)};
 const removeNode=()=>{if(!selected)return;setNodes(v=>v.filter(n=>n.id!==selected));setEdges(v=>v.filter(e=>e.from!==selected&&e.to!==selected));setSelected(null)};
 const exportProject=()=>downloadText(`${project.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'ark-app'}.ark.json`,JSON.stringify({schema:'ark-project',version:3,project,nodes,edges},null,2),'application/json');
 const importProject=()=>fileInput.current?.click();
 const onImport=async e=>{try{const f=e.target.files?.[0];if(!f)return;const data=JSON.parse(await f.text());setProject(data.project||'My ARK App');setNodes(data.nodes||[]);setEdges(data.edges||[]);setSelected(data.nodes?.[0]?.id||null);setBuildLog('Project imported.')}catch{setBuildLog('Invalid ARK project file.')}e.target.value=''};
 const build=()=>{const invalid=edges.some(e=>!nodes.find(n=>n.id===e.from)||!nodes.find(n=>n.id===e.to));if(invalid)return setBuildLog('Build blocked: invalid connection detected.');setBuildLog(`Validated ${nodes.length} nodes / ${edges.length} links.`);const g=generateAndroidProject(project,nodes);setGenerated(g)};
 const downloadGenerated=()=>{if(!generated)return;const manifest=Object.entries(generated.files).map(([p,c])=>`===== ${p} =====\n${c}\n`).join('\n');downloadText(`${generated.appName.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-android-project.txt`,manifest)};
 return <div className="app">
  <input ref={fileInput} type="file" accept=".json,.ark.json" hidden onChange={onImport}/>
  <header><div className="brand"><span>ARK</span> APP BUILDER <small>V0.3 GENERATOR ENGINE</small></div><input className="project-name" value={project} onChange={e=>setProject(e.target.value)}/><div className="actions"><button onClick={importProject}>Import</button><button onClick={exportProject}>Export</button><button onClick={()=>{localStorage.setItem('ark-project-v3',JSON.stringify({project,nodes,edges}));setBuildLog('Saved locally.')}}>Save</button><button onClick={build} className="build">Generate Android</button></div></header>
  <main>
   <aside className="toolbox"><h3>NODES</h3><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search components..."/>{filtered.map(([group,items])=><section key={group}><h4>{group}</h4>{items.map(item=><button className="node-tool" key={item} onClick={()=>addNode(item)}><b>{item[0]}</b>{item}</button>)}</section>)}</aside>
   <section className="workspace"><div className="workspace-bar"><span>VISUAL GRAPH / {nodes.length} NODES / {edges.length} LINKS</span><div><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><b>{Math.round(zoom*100)}%</b><button onClick={()=>setZoom(z=>Math.min(1.6,z+.1))}>+</button><button onClick={autoConnect}>Auto Connect</button><button onClick={()=>{setNodes([]);setEdges([]);setSelected(null)}}>Clear</button></div></div>
    <div className="canvas" style={{transform:`scale(${zoom})`}} onClick={()=>setSelected(null)}>
      <svg className="links" width="2000" height="1200">{edges.map(e=>{const a=nodes.find(n=>n.id===e.from),b=nodes.find(n=>n.id===e.to);if(!a||!b)return null;return <g key={e.id}><line x1={a.x+190} y1={a.y+70} x2={b.x} y2={b.y+70}/><circle cx={(a.x+190+b.x)/2} cy={(a.y+b.y+140)/2} r="4"/></g>})}</svg>
      {nodes.map(n=><div key={n.id} className={`node ${selected===n.id?'selected':''}`} style={{left:n.x,top:n.y}} onClick={e=>{e.stopPropagation();if(connectFrom)connect(connectFrom,n.id);else setSelected(n.id)}}><button className="port in" onClick={e=>e.stopPropagation()} title="Input">IN</button><div className="node-head"><span>{n.type}</span><i>●</i></div><strong>{n.title}</strong><div className="ports"><button onClick={e=>{e.stopPropagation();setConnectFrom(n.id)}} className={connectFrom===n.id?'armed':''}>OUT</button></div>{edges.some(e=>e.from===n.id)&&<div className="link-label">CONNECTED</div>}</div>)}
      {!nodes.length&&<div className="empty"><strong>BUILD WITHOUT CODE</strong><p>Add nodes → configure properties → tap OUT → tap another node.</p><p>Example: Event → Camera → AI Vision → Object Detector → Text</p></div>}
    </div></section>
   <aside className="inspector"><h3>PROPERTIES</h3>{selectedNode?<><label>Node name</label><input value={selectedNode.title} onChange={e=>updateNode(selectedNode.id,{title:e.target.value})}/>{Object.entries(selectedNode.props).map(([k,v])=><div key={k}><label>{k}</label><input value={String(v)} onChange={e=>updateProp(k,e.target.value)}/></div>)}<label>Enabled</label><input type="checkbox" checked={selectedNode.enabled} onChange={e=>updateNode(selectedNode.id,{enabled:e.target.checked})}/><button className="connect" onClick={()=>setConnectFrom(selectedNode.id)}>Connect OUT</button><button className="delete" onClick={removeNode}>Delete Node</button></>:<p>Select a node. Use OUT → another node to create a connection.</p>}<hr/><h3>GENERATOR</h3><div className="status">{buildLog}</div>{generated&&<><div className="generated"><b>Android project ready</b><span>Package: {generated.packageName}</span><span>Permissions: {generated.permissions.length||'none'}</span></div><button className="download" onClick={downloadGenerated}>Download Android Sources</button></>}<div className="feature">✓ Visual graph + edges</div><div className="feature">✓ Project JSON v3</div><div className="feature">✓ Android source generation</div><div className="feature">✓ Permission inference</div><div className="feature">◌ Full UI code mapping</div><div className="feature">◌ Direct APK compiler</div></aside>
  </main></div>;
}
createRoot(document.getElementById('root')).render(<App />);
